---
# Language: Ansible

# https://github.com/linux-system-roles/mssql

- name: Install SQL Server 2022 AG read scale
  hosts: all
  
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_version: 2022
    mssql_password: "p@55w0rD"
    mssql_edition: Evaluation
    mssql_install_powershell: true
    mssql_enable_sqlagent: true
    mssql_rhel_tuned: false
    # false for centos container
    mssql_manage_firewall: false
    # read scale
    mssql_ha_configure: true
    mssql_ha_ag_cluster_type: none
    mssql_ha_endpoint_port: 5022
    mssql_ha_cert_name: AGReadReplicaCert
    mssql_ha_master_key_password: "p@55w0rD1"
    mssql_ha_private_key_password: "p@55w0rD2"
    mssql_ha_reset_cert: false
    mssql_ha_endpoint_name: AGReadReplicaEndpoint
    mssql_ha_ag_name: AGReadReplica
    #mssql_ha_db_names:
    #  - AGDB1
    #  - AGDB2
    mssql_ha_login: AGReadReplicaLogin
    mssql_ha_login_password: "p@55w0rD3"
    # Install Ola Hallengren's Maintenance Solution
    # https://ola.hallengren.com/
    mssql_post_input_sql_file: MaintenanceSolution.sql

  #become: yes
  #become_user: root

  roles:
    - role: 'roles/mssql'

  post_tasks:
    - include_tasks: ./tasks/install-dbatools.yml

     
    
