---

name: SQL Server 2022
- hosts: all


tasks:
- name: Copy a single file
  ansible.windows.win_copy:
    src: dbatools/dbatools.2.0.2.nupkg
    dest: C:\Temp\dbatools.2.0.2.nupkg

- name: Copy a single file
  ansible.windows.win_copy:
    src: dbatools/dbatools.library.2023.5.5.nupkg
    dest: C:\Temp\dbatools.library.2023.5.5.nupkg

- name: Copy a single file
  ansible.windows.win_copy:
    src: dbatools/Microsoft.PackageManagement.NuGetProvider.dll
    dest: C:\Temp\Microsoft.PackageManagement.NuGetProvider.dll

- name: Install dbatools module
  ansible.windows.win_powershell:
    script: |
    Register-PSRepository -Name LocalPSRepo -SourceLocation '\\localhost\PSRepoLocal\' -ScriptSourceLocation '\\localhost\PSRepoLocal\' -InstallationPolicy Trusted
    Install-Module -Name dbatools -Repository LocalPSRepo -Force
    Set-PSRepository -Name LocalPSRepo -InstallationPolicy Untrusted

- name: Install SQL Server 2022 using dbatools
  ansible.windows.win_powershell:
    script: |
    Load-Module dbatools
    Install-DbaInstance -Version 2022 -Feature Default 
